import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      <body className={inter.className}>
        <div className="max-w-5xl mx-auto px-4 sm:px-6 py-8">
          <Navbar />
        </div>

        <main className="max-w-5xl mx-auto px-4 sm:px-6">{children}</main>
      </body>
    </html>
  );
}
